#!/bin/bash

echo "🎬 TMDB API Setup for Phase 2 Enhancement 1"
echo "============================================="
echo ""
echo "To enable rich metadata integration, you need a TMDB API key."
echo ""
echo "Steps to get your TMDB API key:"
echo "1. Go to https://www.themoviedb.org/settings/api"
echo "2. Create an account or log in"
echo "3. Request an API key (it's free)"
echo "4. Copy your API key"
echo ""
echo "Once you have your API key, update the plex-data-exporter.py file:"
echo "Change this line:"
echo "TMDB_API_KEY = \"your_tmdb_api_key_here\""
echo ""
echo "To:"
echo "TMDB_API_KEY = \"your_actual_api_key_here\""
echo ""
echo "Benefits of TMDB integration:"
echo "✅ Rich movie metadata (cast, crew, genres, ratings)"
echo "✅ Similar movie recommendations"
echo "✅ Enhanced genre analysis"
echo "✅ Director and actor-based recommendations"
echo "✅ Movie posters and backdrops"
echo "✅ Production company insights"
echo ""
echo "Cost: FREE (TMDB API is free for personal use)"
echo "Rate limit: 40 requests per 10 seconds"
echo ""
echo "The system will work without TMDB integration, but with basic recommendations only."
echo ""
